# Generated by Django 2.2.12 on 2020-04-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Senior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('position', models.CharField(max_length=60)),
                ('greeting', models.CharField(max_length=130)),
                ('created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
